name: oildrop_mobile
description: Mobile Flutter client for Oildrop (demo web app reference) with Firebase auth & biometric groundwork.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  cloud_functions: ^4.5.5
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.5

  # For future: http, intl, etc.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
